import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/section/common/navbar";
import Footer from "@/components/section/common/footer";
import LogoSlider from "@/components/section/ui/rotatingimg";
import BottomNavbar from "@/components/section/common/navbar";
import Project52Button from "@/components/section/ui/Project52Button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
        <Project52Button />
        <Navbar />
        <LogoSlider />
        <Footer />
      </body>
    </html>
  );
}
